services:
  rssreader:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "26080:8090"
    volumes:
      - ./pb_data:/app/pb_data
    environment:
       - LLM_API_KEY=xxxDUMMYxxx
       - LLM_BASE_URL=https://openrouter.ai/api/v1/

