services:
  rssreader:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "26080:8090"
    volumes:
      - ./pb_data:/app/pb_data
    environment:
       - OPENROUTER_API_KEY=xxxDUMMYxxx

