# Project toolchain managed by mise
[tools]
# Go toolchain for PocketBase custom server build/run
# Use a stable minor to receive latest patch updates automatically
go = "1.24"
# Optional: linter (requires asdf plugin availability via mise)
# golangci-lint = "latest"

[tasks]
up = "pocketbase.exe serve --dev --dir E:\\programming\\AI_generative\\fm-rss-reader-pb\\pb_data --hooksDir E:\\programming\\AI_generative\\fm-rss-reader-pb\\pb_hooks --migrationsDir E:\\programming\\AI_generative\\fm-rss-reader-pb\\pb_migrations"

